# Generated by Django 5.2.8 on 2025-11-08 10:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='ارفع صورة المنتج الرئيسية', max_length=255, verbose_name='صورة المنتج'),
        ),
    ]
