# Generated by Django 5.2.8 on 2025-11-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'مستخدمون'},
        ),
    ]
